export const BlogsMockData = [
    {
      "id": 1,
      "type": "blogs",
      "prise": "$349.00",
      "photo": "https://www.ambiance-sticker.com/images/Image/sticker-meuble-marbre-noir-et-dore-3-ambiance-sticker-col-mob-RJ-2246.jpg",
      "header": "Sleek Modern Couch",
      "date_name": "Date:",
      "date": "March 01, 2025",
      "author": "Author:",
      "author_name": "John Doe",
      "description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy. Large tiles were arranged on the counter top plate near the window of the living room, they were connected to the kitchen counter through the opening in the existing building wall. For me, the most important part of improving at photography has been sharing it. Sign up for an Exposure account, or post regularly to Tumblr, or both. Tell people you’re trying to get better at photography.",
      "second_description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy."
    },
    {
      "id": 2,
      "type": "blogs",
      "prise": "$249",
      "photo": "https://cdn.laredoute.com/cdn-cgi/image/width=400,height=400,fit=pad,dpr=1/products/4/3/0/4305c5d035495807f43a2e63a21d6057.jpg",
      "header": "Cozy Rattan Chair",
      "date_name": "Date:",
      "date": "March 01, 2025",
      "author": "Author:",
      "author_name": "Jane Smith",
      "description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy. Large tiles were arranged on the counter top plate near the window of the living room, they were connected to the kitchen counter through the opening in the existing building wall. For me, the most important part of improving at photography has been sharing it. Sign up for an Exposure account, or post regularly to Tumblr, or both. Tell people you’re trying to get better at photography.",
      "second_description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy."
    },
    {
      "id": 3,
      "type": "blogs",
      "prise": "$79.00",
      "photo": "https://media.johnlewiscontent.com/i/JohnLewis/anyday-rental-living-t-290321?fmt=auto",
      "header": "Sturdy Wooden Bookshelf",
      "date_name": "Date:",
      "date": "March 01, 2025",
      "author": "Author:",
      "author_name": "Alice Johnson",
      "description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy. Large tiles were arranged on the counter top plate near the window of the living room, they were connected to the kitchen counter through the opening in the existing building wall. For me, the most important part of improving at photography has been sharing it. Sign up for an Exposure account, or post regularly to Tumblr, or both. Tell people you’re trying to get better at photography.",
      "second_description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy."
    },
    {
      "id": 4,
      "type": "blogs",
      "prise": "$430.00",
      "photo": "https://m.media-amazon.com/images/I/71D5e8wn+mL.jpg",
      "header": "Elegant Glass Dining Table",
      "date_name": "Date:",
      "date": "March 01, 2025",
      "author": "Author:",
      "author_name": "Michael Lee",
      "description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy. Large tiles were arranged on the counter top plate near the window of the living room, they were connected to the kitchen counter through the opening in the existing building wall. For me, the most important part of improving at photography has been sharing it. Sign up for an Exposure account, or post regularly to Tumblr, or both. Tell people you’re trying to get better at photography.",
      "second_description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy."
    },
    {
      "id": 5,
      "type": "blogs",
      "prise": "$100.00",
      "photo": "https://www.carltonfurniture.co.uk/images/pages/534-3-Aero%20Bubble%20Sofa%20Set%20%20(19).jpg",
      "header": "Comfortable Lounge Chair",
      "date_name": "Date:",
      "date": "March 01, 2025",
      "author": "Author:",
      "author_name": "Sarah Kim",
      "description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy. Large tiles were arranged on the counter top plate near the window of the living room, they were connected to the kitchen counter through the opening in the existing building wall. For me, the most important part of improving at photography has been sharing it. Sign up for an Exposure account, or post regularly to Tumblr, or both. Tell people you’re trying to get better at photography.",
      "second_description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy."
    },
    {
      "id": 6,
      "type": "blogs",
      "prise": "$300.00",
      "photo": "https://media.johnlewiscontent.com/i/johnlewis/Small-space-furniture-lead?fmt=auto",
      "header": "Vintage Industrial Lamp",
      "date_name": "Date:",
      "date": "March 01, 2025",
      "author": "Author:",
      "author_name": "David Green",
      "description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy. Large tiles were arranged on the counter top plate near the window of the living room, they were connected to the kitchen counter through the opening in the existing building wall. For me, the most important part of improving at photography has been sharing it. Sign up for an Exposure account, or post regularly to Tumblr, or both. Tell people you’re trying to get better at photography.",
      "second_description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy."
    },
     {
        "id": 7,
        "photo": "https://www.ambiance-sticker.com/images/Image/sticker-meuble-marbre-noir-et-dore-3-ambiance-sticker-col-mob-RJ-2246.jpg",
        "header": "Sleek Modern Couch",
        "date_name": "Date:",
        "date": "March 01, 2025",
        "author": "Author:",
        "author_name": "John Doe",
        "description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy. Large tiles were arranged on the counter top plate near the window of the living room, they were connected to the kitchen counter through the opening in the existing building wall. For me, the most important part of improving at photography has been sharing it. Sign up for an Exposure account, or post regularly to Tumblr, or both. Tell people you’re trying to get better at photography.",
        "second_description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy.",
        "type": "home",
        "prise": "$599"
      },
      {
        "id": 8,
        "photo": "https://cdn.laredoute.com/cdn-cgi/image/width=400,height=400,fit=pad,dpr=1/products/4/3/0/4305c5d035495807f43a2e63a21d6057.jpg",
        "header": "Cozy Rattan Chair",
        "date_name": "Date:",
        "date": "March 01, 2025",
        "author": "Author:",
        "author_name": "Jane Smith",
        "description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy. Large tiles were arranged on the counter top plate near the window of the living room, they were connected to the kitchen counter through the opening in the existing building wall. For me, the most important part of improving at photography has been sharing it. Sign up for an Exposure account, or post regularly to Tumblr, or both. Tell people you’re trying to get better at photography.",
        "second_description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy.",
        "type": "home",
        "prise": "$249"
      },
      {
        "id": 9,
        "photo": "https://media.johnlewiscontent.com/i/JohnLewis/anyday-rental-living-t-290321?fmt=auto",
        "header": "Sturdy Wooden Bookshelf",
        "date_name": "Date:",
        "date": "March 01, 2025",
        "author": "Author:",
        "author_name": "Alice Johnson",
        "description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy. Large tiles were arranged on the counter top plate near the window of the living room, they were connected to the kitchen counter through the opening in the existing building wall. For me, the most important part of improving at photography has been sharing it. Sign up for an Exposure account, or post regularly to Tumblr, or both. Tell people you’re trying to get better at photography.",
        "second_description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy.",
        "type": "home",
        "prise": "$349"
      },
      {
        "id": 10,
        "photo": "https://m.media-amazon.com/images/I/71D5e8wn+mL.jpg",
        "header": "Elegant Glass Dining Table",
        "date_name": "Date:",
        "date": "March 01, 2025",
        "author": "Author:",
        "author_name": "Michael Lee",
        "description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy. Large tiles were arranged on the counter top plate near the window of the living room, they were connected to the kitchen counter through the opening in the existing building wall. For me, the most important part of improving at photography has been sharing it. Sign up for an Exposure account, or post regularly to Tumblr, or both. Tell people you’re trying to get better at photography.",
        "second_description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy.",
        "type": "home",
        "prise": "$799"
      },
      {
        "id": 11,
        "photo": "https://www.carltonfurniture.co.uk/images/pages/534-3-Aero%20Bubble%20Sofa%20Set%20%20(19).jpg",
        "header": "Comfortable Lounge Chair",
        "date_name": "Date:",
        "date": "March 01, 2025",
        "author": "Author:",
        "author_name": "Sarah Kim",
        "description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy. Large tiles were arranged on the counter top plate near the window of the living room, they were connected to the kitchen counter through the opening in the existing building wall. For me, the most important part of improving at photography has been sharing it. Sign up for an Exposure account, or post regularly to Tumblr, or both. Tell people you’re trying to get better at photography.",
        "second_description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy.",
        "type": "home",
        "prise": "$499"
      },
      {
        "id": 12,
        "photo": "https://media.johnlewiscontent.com/i/johnlewis/Small-space-furniture-lead?fmt=auto",
        "header": "Vintage Industrial Lamp",
        "date_name": "Date:",
        "date": "March 01, 2025",
        "author": "Author:",
        "author_name": "David Green",
        "description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy. Large tiles were arranged on the counter top plate near the window of the living room, they were connected to the kitchen counter through the opening in the existing building wall. For me, the most important part of improving at photography has been sharing it. Sign up for an Exposure account, or post regularly to Tumblr, or both. Tell people you’re trying to get better at photography.",
        "second_description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy.",
        "type": "home",
        "prise": "$199"
      }, {
        "id": 13,
        "photo": "https://cdn.laredoute.com/cdn-cgi/image/width=400,height=400,fit=pad,dpr=1/products/4/3/0/4305c5d035495807f43a2e63a21d6057.jpg",
        "header": "Cozy Rattan Chair",
        "date_name": "Date:",
        "date": "March 01, 2025",
        "author": "Author:",
        "author_name": "Jane Smith",
        "description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy. Large tiles were arranged on the counter top plate near the window of the living room, they were connected to the kitchen counter through the opening in the existing building wall. For me, the most important part of improving at photography has been sharing it. Sign up for an Exposure account, or post regularly to Tumblr, or both. Tell people you’re trying to get better at photography.",
        "second_description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy.",
        "type": "home",
        "prise": "$249"
      },
      {
        "id": 14,
        "photo": "https://media.johnlewiscontent.com/i/JohnLewis/anyday-rental-living-t-290321?fmt=auto",
        "header": "Sturdy Wooden Bookshelf",
        "date_name": "Date:",
        "date": "March 01, 2025",
        "author": "Author:",
        "author_name": "Alice Johnson",
        "description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy. Large tiles were arranged on the counter top plate near the window of the living room, they were connected to the kitchen counter through the opening in the existing building wall. For me, the most important part of improving at photography has been sharing it. Sign up for an Exposure account, or post regularly to Tumblr, or both. Tell people you’re trying to get better at photography.",
        "second_description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy.",
        "type": "home",
        "prise": "$349",
      },
      {
        "id": 15,
        "type": "popular",
        "prise": "$349.00",
        "photo": "https://www.ambiance-sticker.com/images/Image/sticker-meuble-marbre-noir-et-dore-3-ambiance-sticker-col-mob-RJ-2246.jpg",
        "header": "Sleek Modern Couch",
        "date_name": "Date:",
        "date": "March 01, 2025",
        "author": "Author:",
        "author_name": "John Doe",
        "description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy. Large tiles were arranged on the counter top plate near the window of the living room, they were connected to the kitchen counter through the opening in the existing building wall. For me, the most important part of improving at photography has been sharing it. Sign up for an Exposure account, or post regularly to Tumblr, or both. Tell people you’re trying to get better at photography.",
        "second_description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy."
      },
      {
        "id": 16,
        "type": "popular",
        "prise": "$249",
        "photo": "https://cdn.laredoute.com/cdn-cgi/image/width=400,height=400,fit=pad,dpr=1/products/4/3/0/4305c5d035495807f43a2e63a21d6057.jpg",
        "header": "Cozy Rattan Chair",
        "date_name": "Date:",
        "date": "March 01, 2025",
        "author": "Author:",
        "author_name": "Jane Smith",
        "description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy. Large tiles were arranged on the counter top plate near the window of the living room, they were connected to the kitchen counter through the opening in the existing building wall. For me, the most important part of improving at photography has been sharing it. Sign up for an Exposure account, or post regularly to Tumblr, or both. Tell people you’re trying to get better at photography.",
        "second_description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy."
      },
      {
        "id": 17,
        "type": "popular",
        "prise": "$79.00",
        "photo": "https://media.johnlewiscontent.com/i/JohnLewis/anyday-rental-living-t-290321?fmt=auto",
        "header": "Sturdy Wooden Bookshelf",
        "date_name": "Date:",
        "date": "March 01, 2025",
        "author": "Author:",
        "author_name": "Alice Johnson",
        "description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy. Large tiles were arranged on the counter top plate near the window of the living room, they were connected to the kitchen counter through the opening in the existing building wall. For me, the most important part of improving at photography has been sharing it. Sign up for an Exposure account, or post regularly to Tumblr, or both. Tell people you’re trying to get better at photography.",
        "second_description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy."
      },
      {
        "id": 18,
        "type": "popular",
        "prise": "$430.00",
        "photo": "https://m.media-amazon.com/images/I/71D5e8wn+mL.jpg",
        "header": "Elegant Glass Dining Table",
        "date_name": "Date:",
        "date": "March 01, 2025",
        "author": "Author:",
        "author_name": "Michael Lee",
        "description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy. Large tiles were arranged on the counter top plate near the window of the living room, they were connected to the kitchen counter through the opening in the existing building wall. For me, the most important part of improving at photography has been sharing it. Sign up for an Exposure account, or post regularly to Tumblr, or both. Tell people you’re trying to get better at photography.",
        "second_description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy."
      },
      {
        "id": 19,
        "type": "popular",
        "prise": "$349.00",
        "photo": "https://www.archerssleepcentre.co.uk/images/products/large/_61284.webp",
        "header": "Sleek Modern Couch",
        "date_name": "Date:",
        "date": "March 01, 2025",
        "author": "Author:",
        "author_name": "John Doe",
        "description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy. Large tiles were arranged on the counter top plate near the window of the living room, they were connected to the kitchen counter through the opening in the existing building wall. For me, the most important part of improving at photography has been sharing it. Sign up for an Exposure account, or post regularly to Tumblr, or both. Tell people you’re trying to get better at photography.",
        "second_description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy."
      },
      {
        "id": 20,
        "type": "popular",
        "prise": "$249",
        "photo": "https://img.freepik.com/premium-photo/bright-airy-living-room-corner-with-cozy-rattan-chair-neutral-tones-natural-materials-soft-lighting-large-windows-creating-serene-minimalist-space-relaxation_1219093-40683.jpg",
        "header": "Cozy Rattan Chair",
        "date_name": "Date:",
        "date": "March 01, 2025",
        "author": "Author:",
        "author_name": "Jane Smith",
        "description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy. Large tiles were arranged on the counter top plate near the window of the living room, they were connected to the kitchen counter through the opening in the existing building wall. For me, the most important part of improving at photography has been sharing it. Sign up for an Exposure account, or post regularly to Tumblr, or both. Tell people you’re trying to get better at photography.",
        "second_description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy."
      },
      {
        "id": 21,
        "type": "popular",
        "prise": "$79.00",
        "photo": "https://i5.walmartimages.com/seo/Dextrus-5-Tier-Bookshelf-Sturdy-Wood-Storage-Bookcase-Shelves-with-Metal-Frame-Plant-Display-for-Living-Room-Office-Rustic-Brown_ab546ce9-0a33-4454-93fe-15b438b746a3.9d56a7ab072a744c0f221459ecd62092.jpeg?odnHeight=612&odnWidth=612&odnBg=FFFFFF",
        "header": "Sturdy Wooden Bookshelf",
        "date_name": "Date:",
        "date": "March 01, 2025",
        "author": "Author:",
        "author_name": "Alice Johnson",
        "description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy. Large tiles were arranged on the counter top plate near the window of the living room, they were connected to the kitchen counter through the opening in the existing building wall. For me, the most important part of improving at photography has been sharing it. Sign up for an Exposure account, or post regularly to Tumblr, or both. Tell people you’re trying to get better at photography.",
        "second_description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy."
      },
      {
        "id": 22,
        "type": "popular",
        "prise": "$430.00",
        "photo": "https://i5.walmartimages.com/seo/Modway-Provision-47-Round-Dining-Table-in-Black_24f06e2c-b756-4b75-947e-0435443f4756.c673cabf4c1b634c8474905b55db601a.jpeg",
        "header": "Elegant Glass Dining Table",
        "date_name": "Date:",
        "date": "March 01, 2025",
        "author": "Author:",
        "author_name": "Michael Lee",
        "description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy. Large tiles were arranged on the counter top plate near the window of the living room, they were connected to the kitchen counter through the opening in the existing building wall. For me, the most important part of improving at photography has been sharing it. Sign up for an Exposure account, or post regularly to Tumblr, or both. Tell people you’re trying to get better at photography.",
        "second_description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy."
      },
      {
        "id": 23,
        "type": "popular",
        "prise": "$349.00",
        "photo": "https://remodernliving.com/wp-content/uploads/2021/12/vitis-sofa-sectional-rom.jpg",
        "header": "Sleek Modern Couch",
        "date_name": "Date:",
        "date": "March 01, 2025",
        "author": "Author:",
        "author_name": "John Doe",
        "description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy. Large tiles were arranged on the counter top plate near the window of the living room, they were connected to the kitchen counter through the opening in the existing building wall. For me, the most important part of improving at photography has been sharing it. Sign up for an Exposure account, or post regularly to Tumblr, or both. Tell people you’re trying to get better at photography.",
        "second_description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy."
      },
      {
        "id": 24,
        "type": "popular",
        "prise": "$249",
        "photo": "https://img4.dhresource.com/webp/m/f3/albu/jc/s/14/c97948fb-769f-4fb7-b034-7b51b8174b84.jpg",
        "header": "Cozy Rattan Chair",
        "date_name": "Date:",
        "date": "March 01, 2025",
        "author": "Author:",
        "author_name": "Jane Smith",
        "description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy. Large tiles were arranged on the counter top plate near the window of the living room, they were connected to the kitchen counter through the opening in the existing building wall. For me, the most important part of improving at photography has been sharing it. Sign up for an Exposure account, or post regularly to Tumblr, or both. Tell people you’re trying to get better at photography.",
        "second_description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy."
      },
      {
        "id": 25,
        "type": "new",
        "prise": "$100.00",
        "photo": "https://officesnapshots.com/wp-content/uploads/2024/08/cropped-image-25-1722977814.jpeg",
        "header": "Comfortable Lounge Chair",
        "date_name": "Date:",
        "date": "March 01, 2025",
        "author": "Author:",
        "author_name": "Sarah Kim",
        "description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy. Large tiles were arranged on the counter top plate near the window of the living room, they were connected to the kitchen counter through the opening in the existing building wall. For me, the most important part of improving at photography has been sharing it. Sign up for an Exposure account, or post regularly to Tumblr, or both. Tell people you’re trying to get better at photography.",
        "second_description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy."
      },
      {
        "id": 26,
        "type": "new",
        "prise": "$300.00",
        "photo": "https://m.media-amazon.com/images/I/81hrBDxIVnL.jpg",
        "header": "Comfy Modern Sofa",
        "date_name": "Date:",
        "date": "March 01, 2025",
        "author": "Author:",
        "author_name": "David Green",
        "description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy. Large tiles were arranged on the counter top plate near the window of the living room, they were connected to the kitchen counter through the opening in the existing building wall. For me, the most important part of improving at photography has been sharing it. Sign up for an Exposure account, or post regularly to Tumblr, or both. Tell people you’re trying to get better at photography.",
        "second_description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy."
      },
       {
          "id": 27,
          "type": "new",
          "photo": "https://inmarwar.com/cdn/shop/files/tv-unit-with-two-doors-and-two-drawer-made-of-solid-acacia-wood-530587_ed9d8600-0051-4b32-b8a9-1f77670170a2.jpg?v=1740985405",
          "header": "TV Drawer",
          "date_name": "Date:",
          "date": "March 01, 2025",
          "author": "Author:",
          "author_name": "John Doe",
          "description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy. Large tiles were arranged on the counter top plate near the window of the living room, they were connected to the kitchen counter through the opening in the existing building wall. For me, the most important part of improving at photography has been sharing it. Sign up for an Exposure account, or post regularly to Tumblr, or both. Tell people you’re trying to get better at photography.",
          "second_description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy.",
          "prise": "$599"
        },
        {
          "id": 29,
          "type": "new",
          "photo": "https://gvawood.com/cdn/shop/files/O1CN01Ss3Hue1nJefr8ZY24__1105025069.jpg?v=1741813705&width=750",
          "header": "TV Drawer",
          "date_name": "Date:",
          "date": "March 01, 2025",
          "author": "Author:",
          "author_name": "John Doe",
          "description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy. Large tiles were arranged on the counter top plate near the window of the living room, they were connected to the kitchen counter through the opening in the existing building wall. For me, the most important part of improving at photography has been sharing it. Sign up for an Exposure account, or post regularly to Tumblr, or both. Tell people you’re trying to get better at photography.",
          "second_description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy.",
          "prise": "$599"
        },
        {
          "id": 29,
          "type":"discounted",
          "photo": "https://media.johnlewiscontent.com/i/JohnLewis/anyday-rental-living-t-290321?fmt=auto",
          "header": "Sturdy Wooden Bookshelf",
          "date_name": "Date:",
          "date": "March 01, 2025",
          "author": "Author:",
          "author_name": "Alice Johnson",
          "description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy. Large tiles were arranged on the counter top plate near the window of the living room, they were connected to the kitchen counter through the opening in the existing building wall. For me, the most important part of improving at photography has been sharing it. Sign up for an Exposure account, or post regularly to Tumblr, or both. Tell people you’re trying to get better at photography.",
          "second_description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy.",
          "old_prise": "$349",
          "new_price": "$300"
        },
        {
          "id": 30,
          "type":"discounted",
          "photo": "https://www.ambiance-sticker.com/images/Image/sticker-meuble-marbre-noir-et-dore-3-ambiance-sticker-col-mob-RJ-2246.jpg",
          "header": "Sleek Modern Couch",
          "date_name": "Date:",
          "date": "March 01, 2025",
          "author": "Author:",
          "author_name": "John Doe",
          "description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy. Large tiles were arranged on the counter top plate near the window of the living room, they were connected to the kitchen counter through the opening in the existing building wall. For me, the most important part of improving at photography has been sharing it. Sign up for an Exposure account, or post regularly to Tumblr, or both. Tell people you’re trying to get better at photography.",
          "second_description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy.",
          "old_prise": "$1.500",
          "new_price": "$1.299"
        },
        {
          "id": 31,
          "type":"discounted",
          "photo": "https://cdn.laredoute.com/cdn-cgi/image/width=400,height=400,fit=pad,dpr=1/products/4/3/0/4305c5d035495807f43a2e63a21d6057.jpg",
          "header": "Cozy Rattan Chair",
          "date_name": "Date:",
          "date": "March 01, 2025",
          "author": "Author:",
          "author_name": "Jane Smith",
          "description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy. Large tiles were arranged on the counter top plate near the window of the living room, they were connected to the kitchen counter through the opening in the existing building wall. For me, the most important part of improving at photography has been sharing it. Sign up for an Exposure account, or post regularly to Tumblr, or both. Tell people you’re trying to get better at photography.",
          "second_description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy.",
          "old_prise": "$249",
          "new_price": "$189"
        },
        {
          "id": 32,
          "type":"best-seller",
          "photo": "https://berkowitz.com.au/wp-content/uploads/2023/04/IMG-manual-recliners.jpg",
          "header": "Cozy Office Chair",
          "date_name": "Date:",
          "date": "March 01, 2025",
          "author": "Author:",
          "author_name": "Jane Smith",
          "description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy. Large tiles were arranged on the counter top plate near the window of the living room, they were connected to the kitchen counter through the opening in the existing building wall. For me, the most important part of improving at photography has been sharing it. Sign up for an Exposure account, or post regularly to Tumblr, or both. Tell people you’re trying to get better at photography.",
          "second_description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy.",
          "price": "$220"
        },
        {
          "id": 33,
          "type":"best-seller",
          "photo": "https://cdn.laredoute.com/cdn-cgi/image/width=400,height=400,fit=pad,dpr=1/products/4/3/0/4305c5d035495807f43a2e63a21d6057.jpg",
          "header": "Cozy Rattan Chair",
          "date_name": "Date:",
          "date": "March 01, 2025",
          "author": "Author:",
          "author_name": "Jane Smith",
          "description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy. Large tiles were arranged on the counter top plate near the window of the living room, they were connected to the kitchen counter through the opening in the existing building wall. For me, the most important part of improving at photography has been sharing it. Sign up for an Exposure account, or post regularly to Tumblr, or both. Tell people you’re trying to get better at photography.",
          "second_description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy.",
          "price": "$189"
        },
        {
          "id": 34,
          "type":"best-seller",
          "photo": "https://gvawood.com/cdn/shop/files/O1CN01Ss3Hue1nJefr8ZY24__1105025069.jpg?v=1741813705&width=750",
          "header": "TV Drawer",
          "date_name": "Date:",
          "date": "March 01, 2025",
          "author": "Author:",
          "author_name": "Jane Smith",
          "description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy. Large tiles were arranged on the counter top plate near the window of the living room, they were connected to the kitchen counter through the opening in the existing building wall. For me, the most important part of improving at photography has been sharing it. Sign up for an Exposure account, or post regularly to Tumblr, or both. Tell people you’re trying to get better at photography.",
          "second_description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy.",
          "price": "$599"
        },
        {
          "id": 35,
          "type":"on-sale",
          "photo": "https://berkowitz.com.au/wp-content/uploads/2023/04/IMG-manual-recliners.jpg",
          "header": "Cozy Office Chair",
          "date_name": "Date:",
          "date": "March 01, 2025",
          "author": "Author:",
          "author_name": "Jane Smith",
          "description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy. Large tiles were arranged on the counter top plate near the window of the living room, they were connected to the kitchen counter through the opening in the existing building wall. For me, the most important part of improving at photography has been sharing it. Sign up for an Exposure account, or post regularly to Tumblr, or both. Tell people you’re trying to get better at photography.",
          "second_description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy.",
          "old_price": "$200",
          "new_price": "$199"
        },
        {
          "id": 36,
          "type":"on-sale",
          "photo": "https://cdn.laredoute.com/cdn-cgi/image/width=400,height=400,fit=pad,dpr=1/products/4/3/0/4305c5d035495807f43a2e63a21d6057.jpg",
          "header": "Cozy Rattan Chair",
          "date_name": "Date:",
          "date": "March 01, 2025",
          "author": "Author:",
          "author_name": "Jane Smith",
          "description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy. Large tiles were arranged on the counter top plate near the window of the living room, they were connected to the kitchen counter through the opening in the existing building wall. For me, the most important part of improving at photography has been sharing it. Sign up for an Exposure account, or post regularly to Tumblr, or both. Tell people you’re trying to get better at photography.",
          "second_description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy.",
          "old_price": "$195",
          "new_price": "$189"
        },
        {
          "id": 37,
          "type":"on-sale",
          "photo": "https://gvawood.com/cdn/shop/files/O1CN01Ss3Hue1nJefr8ZY24__1105025069.jpg?v=1741813705&width=750",
          "header": "TV Drawer",
          "date_name": "Date:",
          "date": "March 01, 2025",
          "author": "Author:",
          "author_name": "Jane Smith",
          "description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy. Large tiles were arranged on the counter top plate near the window of the living room, they were connected to the kitchen counter through the opening in the existing building wall. For me, the most important part of improving at photography has been sharing it. Sign up for an Exposure account, or post regularly to Tumblr, or both. Tell people you’re trying to get better at photography.",
          "second_description": "It is accompanied by a case that can contain up to three different diffusers and can be used for dry storage of loose tea. The perfect way to enjoy brewing tea on low hanging fruit to identify. Lighting is a minimal residence located in Tokyo, Japan, designed by Spozy.",
          "old_price": "$249",
          "new_price": "$245"
        },
    ]
    
   

  